"""Football AI Engine version and default calibration profile."""

ENGINE_NAME = "Football AI Engine"
ENGINE_CODE = "FAE"
ENGINE_VERSION = "2.13.1"
SCHEMA_VERSION = "2.5"

DIMENSION_WEIGHTS = {
    "handicap": 0.20,
    "euro": 0.18,
    "over_under": 0.12,
    "sporttery": 0.16,
    "motivation": 0.10,
    "injuries": 0.08,
    "history": 0.06,
    "form": 0.10,
}

DEFAULT_RULE_WEIGHTS = {
    "euro-home-support": 1.00,
    "euro-away-support": 1.00,
    "euro-draw-support": 0.90,
    "asian-line-home": 1.00,
    "asian-line-away": 1.00,
    "asian-home-water": 0.85,
    "asian-away-water": 0.85,
    "market-consensus-home": 1.10,
    "market-consensus-away": 1.10,
    "recent-form-home": 0.90,
    "recent-form-away": 0.90,
    "history-home": 0.65,
    "history-away": 0.65,
    "total-over": 0.90,
    "total-under": 0.90,
    "hot-overheat": 1.00,
    "handicap-drop": 1.00,
    "euro-asian-divergence": 1.00,
    "market-data-anomaly": 1.00,
    "deep-high-water": 1.00,
    "cup-variance": 1.00,
    "data-quality": 1.00,
    "history-draw-favorite-170-189": 1.00,
    "history-draw-strong-favorite-filter": 1.00,
    "history-draw-odds-400-499-filter": 1.00,
    "history-away-favorite-150-209-risk": 1.00,
    "history-draw-league-prior": 1.00,
    "history-hhad-plus1-draw-270-319": 1.00,
    "history-hhad-minus1-draw-320-399": 1.00,
    "history-hhad-draw-small-rise": 1.00,
    "history-hhad-draw-400-499-filter": 1.00,
    "history-hhad-draw-league-prior": 1.00,
}

VERSION_MANIFEST = {
    "name": ENGINE_NAME,
    "code": ENGINE_CODE,
    "version": ENGINE_VERSION,
    "schema_version": SCHEMA_VERSION,
    "features": [
        "mygoal 赔率与盘口归一化",
        "盘口类型 A-G 分类",
        "八维评分、星级与概率输出",
        "固定推荐、每日排名和危险盘口",
        "赛后复盘与规则权重自动调节",
        "版本化 Skill 候选、历史验证、发布与回滚",
        "基本面扩展接口：排名、近期、交锋、赛程、伤停、首发、天气",
        "跨场星级校准、欧亚背离与异常数据自动降级",
        "主选/防选分层与未校准概率口径标识",
        "玩法级赔率价值指数、投注分与市场去水概率",
        "盘口可信度评分及不下注决策层",
        "联赛历史画像、时间衰减基线及历史隐性偏移",
        "上盘水位风险归因、联赛同类模式不穿率及研判复盘闭环",
        "普通平局与竞彩让平独立雷达、核心/观察分层及赛后单独结算",
        "平/让平雷达分层升级：核心推荐与小试候选分离，避免过严门槛导致零推荐",
        "历史赔率区间、让球数、联赛与初即时变化的保守概率校准",
        "强热门不穿场景下的普通平/竞彩让平雷达纠偏",
        "欧赔亚盘推热门但竞彩受让低赔保护时的热门降级护栏",
        "联赛模板指数：平局、让平、大小球和冷门筛选层",
        "爆冷预警扫描器：盘口降级、平赔压低与热门穿盘风险评分",
        "方向强度与赢球差护栏：区分小球和平局，并在真实升深高总球时校正让平/穿盘主次序",
        "竞彩让球确定性语义护栏：精确分差主次保护、复盘文本校正及错误学习候选拦截",
        "双选复盘按比赛去重，并同时报告覆盖率与逐项等额投注收益率",
        "平/让平正式推荐硬门槛：观察层、负赔率价值和历史高风险赔率区间禁止后置晋级",
        "平局与让平雷达每日各展示前三，减少低质量候选噪声",
        "让球双选动态次选：按校准模型概率与去水市场概率重排防选，避免固定保留让平遗漏方向项",
    ],
    "learning_policy": {
        "minimum_samples": 10,
        "decrease_below": 0.60,
        "increase_above": 0.80,
        "step": 0.05,
        "minimum_weight": 0.70,
        "maximum_weight": 1.30,
        "release_mode": "staged",
        "minimum_new_samples": 10,
    },
}
